package com.fullfacing.keycloak4s.authz.client.models

final case class ServerConfiguration(issuer: String,
                                     authorization_endpoint: String,
                                     tokenEndpoint: String,
                                     introspectionEndpoint: String,
                                     userinfoEndpoint: String,
                                     logoutEndpoint: String,
                                     jwksUri: String,
                                     checkSessionIframe: String,
                                     grantTypesSupported: List[String],
                                     responseTypesSupported: List[String],
                                     subjectTypesSupported: List[String],
                                     idTokenSigningAlgValuesSupported: List[String],
                                     userInfoSigningAlgValuesSupported: List[String],
                                     requestObjectSigningAlgValuesSupported: List[String],
                                     responseModesSupported: List[String],
                                     registrationEndpoint: String,
                                     tokenEndpointAuthMethodsSupported: List[String],
                                     tokenEndpointAuthSigningAlgValuesSupported: List[String],
                                     claimsSupported: List[String],
                                     claimTypesSupported: List[String],
                                     claimsParameterSupported: Boolean,
                                     scopesSupported: List[String])