package com.fullfacing.keycloak4s.authz.client.models

final case class ServerConfiguration(issuer: String,
                                     authorization_endpoint: String,
                                     tokenEndpoint: String,
                                     policyEndpoint: String,
                                     introspectionEndpoint: String,
                                     permissionEndpoint: String,
                                     userinfoEndpoint: Option[String] = None,
                                     logoutEndpoint: String,
                                     jwksUri: String,
                                     checkSessionIframe: Option[String] = None,
                                     grantTypesSupported: List[String] = List.empty[String],
                                     responseTypesSupported: List[String] = List.empty[String],
                                     subjectTypesSupported: List[String] = List.empty[String],
                                     idTokenSigningAlgValuesSupported: List[String] = List.empty[String],
                                     userInfoSigningAlgValuesSupported: List[String] = List.empty[String],
                                     requestObjectSigningAlgValuesSupported: List[String] = List.empty[String],
                                     responseModesSupported: List[String] = List.empty[String],
                                     registrationEndpoint: String,
                                     tokenEndpointAuthMethodsSupported: List[String] = List.empty[String],
                                     tokenEndpointAuthSigningAlgValuesSupported: List[String] = List.empty[String],
                                     claimsSupported: List[String] = List.empty[String],
                                     claimTypesSupported: List[String] = List.empty[String],
                                     claimsParameterSupported: Option[Boolean] = None,
                                     scopesSupported: List[String] = List.empty[String])