package com.fullfacing.keycloak4s.authz.monix.bio.models

final case class ServerConfiguration(issuer: String,
                                     authorization_endpoint: String,
                                     token_endpoint: String,
                                     policy_endpoint: String,
                                     introspection_endpoint: String,
                                     end_session_endpoint: String,
                                     registration_endpoint: String,
                                     resource_registration_endpoint: String,
                                     permission_endpoint: String,
                                     userinfo_endpoint: Option[String] = None,
                                     jwks_uri: String,
                                     check_session_iframe: Option[String] = None,
                                     grant_types_supported: List[String] = List.empty[String],
                                     response_types_supported: List[String] = List.empty[String],
                                     subject_types_supported: List[String] = List.empty[String],
                                     id_token_signing_alg_values_supported: List[String] = List.empty[String],
                                     userinfo_signing_alg_values_supported: List[String] = List.empty[String],
                                     request_object_signing_alg_values_supported: List[String] = List.empty[String],
                                     response_modes_supported: List[String] = List.empty[String],
                                     token_endpoint_auth_methods_supported: List[String] = List.empty[String],
                                     token_endpoint_auth_signing_alg_values_supported: List[String] = List.empty[String],
                                     claims_supported: List[String] = List.empty[String],
                                     claim_types_supported: List[String] = List.empty[String],
                                     claims_parameter_supported: Option[Boolean] = None,
                                     scopes_supported: List[String] = List.empty[String],
                                     request_parameter_supported: Option[Boolean] = None,
                                     request_uri_parameter_supported: Option[Boolean] = None)