package com.fullfacing.keycloak4s.core.models

import com.fullfacing.keycloak4s.core.models.enums.Category

final case class AccessToken(acr: Option[String],
                             address: Option[AddressClaimSet],
                             allowed_origins: Option[List[String]],
                             at_hash: Option[String],
                             auth_time: Option[Int],
                             authorization: Option[AccessTokenAuthorization],
                             azp: Option[String],
                             birthdate: Option[String],
                             c_hash: Option[String],
                             category: Option[Category],
                             claims_locales: Option[String],
                             cnf: Option[AccessTokenCertConf],
                             email: Option[String],
                             email_verified: Option[Boolean],
                             exp: Option[String],
                             family_name: Option[String],
                             gender: Option[String],
                             given_name: Option[String],
                             iat: Option[Int],
                             iss: Option[String],
                             jti: Option[String],
                             local: Option[String],
                             middle_name: Option[String],
                             name: Option[String],
                             nickname: Option[String],
                             nonce: Option[String],
                             otherClaims: Option[Map[String, AnyRef]], //The value's type in the Java API is Object.
                             phone_number: Option[String],
                             phone_number_verified: Option[Boolean],
                             picture: Option[String],
                             preferred_username: Option[String],
                             profile: Option[String],
                             realm_access: Option[AccessTokenAccess],
                             s_hash: Option[String],
                             scope: Option[String],
                             session_state: Option[String],
                             sub: Option[String],
                             `trusted-certs`: Option[List[String]],
                             typ: Option[String],
                             updated_at: Option[Long],
                             website: Option[String],
                             zoneinfo: Option[String])