package com.fullfacing.keycloak4s.admin.models

import com.fullfacing.keycloak4s.admin.models.enums.EventType

final case class RealmRepresentation(accessCodeLifespan: Int,
                                     accessCodeLifespanLogin: Int,
                                     accessCodeLifespanUserAction: Int,
                                     accessTokenLifespan: Int,
                                     accessTokenLifespanForImplicitFlow: Int,
                                     accountTheme: Option[String],
                                     actionTokenGeneratedByAdminLifespan: Int,
                                     actionTokenGeneratedByUserLifespan: Int,
                                     adminEventsDetailsEnabled: Boolean,
                                     adminEventsEnabled: Boolean,
                                     adminTheme: Option[String],
                                     attributes: Map[String, String],
                                     authenticationFlows: Option[AuthenticationFlow],
                                     authenticatorConfig: Option[AuthenticatorConfig],
                                     browserFlow: String,
                                     browserSecurityHeaders: Map[String, String],
                                     bruteForceProtected: Boolean,
                                     clientAuthenticationFlow: String,
                                     clientScopeMappings: Map[String, Any] = Map.empty[String, Any],
                                     clientScopes: List[ClientScope],
                                     clients: List[Client],
                                     components: Option[MultivaluedHashMap],
                                     defaultDefaultClientScopes: List[String],
                                     defaultGroups: List[String],
                                     defaultLocale: Option[String],
                                     defaultOptionalClientScopes: List[String],
                                     defaultRoles: List[String],
                                     defaultSignatureAlgorithm: Option[String],
                                     directGrantFlow: String,
                                     displayName: Option[String],
                                     displayNameHtml: Option[String],
                                     dockerAuthenticationFlow: String,
                                     duplicateEmailsAllowed: Boolean,
                                     editUsernameAllowed: Boolean,
                                     emailTheme: Option[String],
                                     enabled: Boolean,
                                     enabledEventTypes: List[EventType],
                                     eventsEnabled: Boolean,
                                     eventsExpiration: Option[Long],
                                     eventsListeners: List[String],
                                     failureFactor: Int,
                                     federatedUsers: List[User],
                                     groups: List[Group],
                                     id: String,
                                     identityProviderMappers: List[IdentityProviderMapper],
                                     identityProviders: List[IdentityProvider],
                                     internationalizationEnabled: Boolean,
                                     keycloakVersion: Option[String],
                                     loginTheme: Option[String],
                                     loginWithEmailAllowed: Boolean,
                                     maxDeltaTimeSeconds: Int,
                                     maxFailureWaitSeconds: Int,
                                     minimumQuickLoginWaitSeconds: Int,
                                     notBefore: Int,
                                     offlineSessionIdleTimeout: Int,
                                     offlineSessionMaxLifespan: Int,
                                     offlineSessionMaxLifespanEnabled: Boolean,
                                     otpPolicyAlgorithm: String,
                                     otpPolicyDigits: Int,
                                     otpPolicyInitialCounter: Int,
                                     otpPolicyLookAheadWindow: Int,
                                     otpPolicyPeriod: Int,
                                     otpPolicyType: String,
                                     passwordPolicy: Option[String],
                                     permanentLockout: Boolean,
                                     protocolMappers: List[ProtocolMapper],
                                     quickLoginCheckMilliSeconds: Long,
                                     realm: String,
                                     refreshTokenMaxReuse: Int,
                                     registrationAllowed: Boolean,
                                     registrationEmailAsUsername: Boolean,
                                     registrationFlow: String,
                                     rememberMe: Boolean,
                                     requiredActions: Option[RequiredActionProvider],
                                     resetCredentialsFlow: String,
                                     resetPasswordAllowed: Boolean,
                                     revokeRefreshToken: Boolean,
                                     roles: Option[RolesRepresentation],
                                     scopeMappings: List[ScopeMapping],
                                     smtpServer: Map[String, Any],
                                     sslRequired: String,
                                     ssoSessionIdleTimeout: Int,
                                     ssoSessionIdleTimeoutRememberMe: Int,
                                     ssoSessionMaxLifespan: Int,
                                     ssoSessionMaxLifespanRememberMe: Int,
                                     supportedLocales: List[String],
                                     userFederationMappers: List[UserFederationMapper],
                                     userFederationProviders: List[UserFederationProvider],
                                     userManagedAccessAllowed: Boolean,
                                     users: Option[User],
                                     verifyEmail: Boolean,
                                     waitIncrementSeconds: Int)

object RealmRepresentation {

  final case class Create(accessCodeLifespan: Option[Int] = None,
                          accessCodeLifespanLogin: Option[Int] = None,
                          accessCodeLifespanUserAction: Option[Int] = None,
                          accessTokenLifespan: Option[Int] = None,
                          accessTokenLifespanForImplicitFlow: Option[Int] = None,
                          accountTheme: Option[String] = None,
                          actionTokenGeneratedByAdminLifespan: Option[Int] = None,
                          actionTokenGeneratedByUserLifespan: Option[Int] = None,
                          adminEventsDetailsEnabled: Option[Boolean] = None,
                          adminEventsEnabled: Option[Boolean] = None,
                          adminTheme: Option[String] = None,
                          attributes: Map[String, String] = Map.empty[String, String],
                          authenticationFlows: Option[AuthenticationFlow] = None,
                          authenticatorConfig: Option[AuthenticatorConfig] = None,
                          browserFlow: Option[String] = None,
                          browserSecurityHeaders: Map[String, String] = Map.empty[String, String],
                          bruteForceProtected: Option[Boolean] = None,
                          clientAuthenticationFlow: Option[String] = None,
                          clientScopeMappings: Map[String, Any] = Map.empty[String, Any],
                          clientScopes: List[ClientScope] = List.empty[ClientScope],
                          clients: List[Client] = List.empty[Client],
                          components: Option[MultivaluedHashMap] = None,
                          defaultDefaultClientScopes: List[String] = List.empty[String],
                          defaultGroups: List[String] = List.empty[String],
                          defaultLocale: Option[String] = None,
                          defaultOptionalClientScopes: List[String] = List.empty[String],
                          defaultRoles: List[String] = List.empty[String],
                          defaultSignatureAlgorithm: Option[String] = None,
                          directGrantFlow: Option[String] = None,
                          displayName: Option[String] = None,
                          displayNameHtml: Option[String] = None,
                          dockerAuthenticationFlow: Option[String] = None,
                          duplicateEmailsAllowed: Option[Boolean] = None,
                          editUsernameAllowed: Option[Boolean] = None,
                          emailTheme: Option[String] = None,
                          enabled: Option[Boolean] = None,
                          enabledEventTypes: List[EventType] = List.empty[EventType],
                          eventsEnabled: Option[Boolean] = None,
                          eventsExpiration: Option[Long] = None,
                          eventsListeners: List[String] = List.empty[String],
                          failureFactor: Option[Int] = None,
                          federatedUsers: List[User] = List.empty[User],
                          groups: List[Group] = List.empty[Group],
                          id: String,
                          identityProviderMappers: List[IdentityProviderMapper] = List.empty[IdentityProviderMapper],
                          identityProviders: List[IdentityProvider] = List.empty[IdentityProvider],
                          internationalizationEnabled: Option[Boolean] = None,
                          keycloakVersion: Option[String] = None,
                          loginTheme: Option[String] = None,
                          loginWithEmailAllowed: Option[Boolean] = None,
                          maxDeltaTimeSeconds: Option[Int] = None,
                          maxFailureWaitSeconds: Option[Int] = None,
                          minimumQuickLoginWaitSeconds: Option[Int] = None,
                          notBefore: Option[Int] = None,
                          offlineSessionIdleTimeout: Option[Int] = None,
                          offlineSessionMaxLifespan: Option[Int] = None,
                          offlineSessionMaxLifespanEnabled: Option[Boolean] = None,
                          otpPolicyAlgorithm: Option[String] = None,
                          otpPolicyDigits: Option[Int] = None,
                          otpPolicyInitialCounter: Option[Int] = None,
                          otpPolicyLookAheadWindow: Option[Int] = None,
                          otpPolicyPeriod: Option[Int] = None,
                          otpPolicyType: Option[String] = None,
                          passwordPolicy: Option[String] = None,
                          permanentLockout: Option[Boolean] = None,
                          protocolMappers: List[ProtocolMapper] = List.empty[ProtocolMapper],
                          quickLoginCheckMilliSeconds: Option[Long] = None,
                          realm: String,
                          refreshTokenMaxReuse: Option[Int] = None,
                          registrationAllowed: Option[Boolean] = None,
                          registrationEmailAsUsername: Option[Boolean] = None,
                          registrationFlow: Option[String] = None,
                          rememberMe: Option[Boolean] = None,
                          requiredActions: Option[RequiredActionProvider] = None,
                          resetCredentialsFlow: Option[String] = None,
                          resetPasswordAllowed: Option[Boolean] = None,
                          revokeRefreshToken: Option[Boolean] = None,
                          roles: Option[RolesRepresentation] = None,
                          scopeMappings: List[ScopeMapping] = List.empty[ScopeMapping],
                          smtpServer: Map[String, Any] = Map.empty[String, Any],
                          sslRequired: Option[String] = None,
                          ssoSessionIdleTimeout: Option[Int] = None,
                          ssoSessionIdleTimeoutRememberMe: Option[Int] = None,
                          ssoSessionMaxLifespan: Option[Int] = None,
                          ssoSessionMaxLifespanRememberMe: Option[Int] = None,
                          supportedLocales: List[String] = List.empty[String],
                          userFederationMappers: List[UserFederationMapper] = List.empty[UserFederationMapper],
                          userFederationProviders: List[UserFederationProvider] = List.empty[UserFederationProvider],
                          userManagedAccessAllowed: Option[Boolean] = None,
                          users: Option[User] = None,
                          verifyEmail: Option[Boolean] = None,
                          waitIncrementSeconds: Option[Int] = None)
}
